export const experienceTechnologies = {
  kompii: [
    "Next.js",
    "TypeScript",
    "Turborepo",
    "pnpm",
    "tRPC",
    "ShadCN UI",
    "Tailwindcss",
    "Expo",
    "React Native",
    "Claude AI",
  ],
  portfolio: ["Astro.js", "Svelte.js", "Tailwindcss", "Shadcn", "v0", "SEO"],
  gma: [
    "Next.js",
    "TypeScript",
    "Tailwindcss",
    "Ruby on Rails",
    "PostgreSQL",
    "Vercel",
    "Railway",
    "Docker",
    "HeroUI",
    "Lucidchart",
    "TDD",
  ],
  eddu: [
    "Next.js",
    "TypeScript",
    "Tailwindcss",
    "Nodejs",
    "PostgreSQL",
    "Google Cloud Platform",
    "Docker",
    "HeroUI",
    "Lucidchart",
  ],
};
